virt: Use MIGRATABLE flag for _srcDomXML
The domain XML used in restore must be retrieved with VIR_DOMAIN_XML_MIGRATABLE
flag from libvirt.  While restore has been working despite the missing flag,
newer libvirt version may refuse to run the VM with errors such as

  libvirtError: unsupported configuration: Target CPU feature count 6 does not match source 0

This patch fixes the problem by adding the flag to the corresponding XMLDesc call.

Bug-Url: https://bugzilla.redhat.com/1466348
Change-Id: Ieb0fed79ee421bab0cc173e217ede14cef32f647
Signed-off-by: Milan Zamazal <mzamazal@redhat.com>