stomp: dispatcher can return empty string
Based on logs provided for BZ I see that dispatcher#recv can return an
empty string which makes parser not to process message and as a result
we get:

exceptions.AttributeError: 'NoneType' object has no attribute 'command'

We need to make sure that we do not attempt to parse the data.


Change-Id: Id2d3553db1b1c7ca86bd0a12a70de6d798fea906
Signed-off-by: pkliczewski <piotr.kliczewski@gmail.com>
Bug-Url: https://bugzilla.redhat.com/1321325
Reviewed-on: https://gerrit.ovirt.org/56996
Continuous-Integration: Jenkins CI
Reviewed-by: Yaniv Bronhaim <ybronhei@redhat.com>
Reviewed-by: Dan Kenigsberg <danken@redhat.com>