api: Handle calls without context
threadlocal.vars is a thread local, so it never has the "context"
attribute unless the thread owning it initialized the value. This
happens only in the RPC threads, before calling the api. When other
threads (e.g. periodic/1) call internal storage apis, we don't have any
context and fail with AttributeError:

2017-05-14 18:39:43,395-0400 ERROR (vmrecovery) [virt.recovery.file]
Error recovering VM: 0b2f5a7f-39c0-4a9d-be14-8ff133e1c496 (recovery:112)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/vdsm/virt/recovery.py", line 110, in load
    res = cif.createVm(params, vmRecover=True)
  File "/usr/share/vdsm/clientIF.py", line 447, in createVm
    vm = Vm(self, vmParams, vmRecover)
  File "<string>", line 2, in __init__
  File "/usr/lib/python2.7/site-packages/vdsm/common/api.py", line 45, in method
    ctx = context_string()
  File "/usr/lib/python2.7/site-packages/vdsm/common/api.py", line 58, in context_string
    ctx = vars.context
AttributeError: 'thread._local' object has no attribute 'context'

Fixed using getattr() instead of accessing vars.context directly.

Change-Id: I79c9fa859a71d538729130e5bc878dd47d2bb702
Bug-Url: https://bugzilla.redhat.com/1112120
Signed-off-by: Nir Soffer <nsoffer@redhat.com>