do not croak on mountpoint with space and digit
A mountpoint with ' 09' gave me the following error

    return _RE_ESCAPE.sub(lambda s: chr(int(s.group()[1:], 8)), path)
ValueError: invalid literal for int() with base 8: '04009'

since the code concatenates 09 to 040 (octal for space).

Change-Id: I33997893320041648187c56e8500348a6850fdfe
Reviewed-on: http://gerrit.ovirt.org/2068
Reviewed-by: Douglas Schilling Landgraf <dougsland@redhat.com>
Tested-by: Douglas Schilling Landgraf <dougsland@redhat.com>
Reviewed-by: Dan Kenigsberg <danken@redhat.com>