hsm: Calling getAllTasks* on non-SPM is a client error
Calling HSM.getAllTasksInfo and HSM.getAllTaksStatuses when the host is
not the SPM raise expected error.

This avoids these unhelpful tracebacks in vdsm log:

2019-06-29 18:27:11,136-0400 ERROR (jsonrpc/5) [storage.TaskManager.Task] (Task='043a2c85-729d-4559-816f-33d44464998b') Unexpected error (task:875)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/vdsm/storage/task.py", line 882, in _run
    return fn(*args, **kargs)
  File "<string>", line 2, in getAllTasksInfo
  File "/usr/lib/python2.7/site-packages/vdsm/common/api.py", line 50, in method
    ret = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/vdsm/storage/hsm.py", line 2237, in getAllTasksInfo
    allTasksInfo = self._pool.getAllTasksInfo()
  File "/usr/lib/python2.7/site-packages/vdsm/storage/securable.py", line 77, in wrapper
    raise SecureError("Secured object is not in safe state")                                                                                                             SecureError: Secured object is not in safe state

2019-06-29 18:27:11,145-0400 ERROR (jsonrpc/7) [storage.TaskManager.Task] (Task='bea107ec-5f73-4c54-926b-3e02334abe0c') Unexpected error (task:875)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/vdsm/storage/task.py", line 882, in _run
    return fn(*args, **kargs)
  File "<string>", line 2, in getAllTasksStatuses
  File "/usr/lib/python2.7/site-packages/vdsm/common/api.py", line 50, in method
    ret = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/vdsm/storage/hsm.py", line 2197, in getAllTasksStatuses
    allTasksStatus = self._pool.getAllTasksStatuses()
  File "/usr/lib/python2.7/site-packages/vdsm/storage/securable.py", line 77, in wrapper
    raise SecureError("Secured object is not in safe state")
SecureError: Secured object is not in safe state

These errors appear 54 times in every OST run, when sosreport try to
collect taks info on the host.

This change eliminates half of these tracebacks. We have additional
SecureError traceback logged by the task. More work is needed to
eliminate these tracebacks.

Change-Id: Ia47e83c9b4d7ba5763334fffa6b0e332e0ef3e3c
Signed-off-by: Nir Soffer <nsoffer@redhat.com>