lvm: Remove lvs from lvs dict while under lock
Removing items directly from the lvs dict outside LVMCache
causes a RuntimeError for modifiying a dictionary while
another code iterates the dict:

  File "/usr/lib/python3.6/site-packages/vdsm/storage/lvm.py", line 734, in _reloadlvs
    staleLVs = [lvName for v, lvName in self._lvs
  File "/usr/lib/python3.6/site-packages/vdsm/storage/lvm.py", line 734, in <listcomp>
    staleLVs = [lvName for v, lvName in self._lvs
RuntimeError: dictionary changed size during iteration

By moving the lvs removal operation into a dedicated
private method in LVMCache protected by the same lock
used for other operations accessing the same dict we
eliminate this unsafe condition.

Change-Id: I4f166ca7ed40f358eb8defca6d2198fc3fdedf8a
Bug-Url: https://bugzilla.redhat.com/1856065
Signed-off-by: Amit Bawer <abawer@redhat.com>