Vm: conf: proper locking in the creation path
We are still getting the error
RuntimeError: dictionary changed size during iteration

When calling Vm.status(), especially during migrations,
so we must review our usage of Vm.conf and ensure the lock
is always used.

Change-Id: I9b754690a41cdc1e1303ddd4c792df5916570872
Bug-Url: https://bugzilla.redhat.com/1318550
Signed-off-by: Francesco Romani <fromani@redhat.com>
Reviewed-on: https://gerrit.ovirt.org/54909
Reviewed-by: Dan Kenigsberg <danken@redhat.com>
Continuous-Integration: Jenkins CI