Revert "tool: Use multipath force reload option (-r) for config changes"
Using "multipath -r" when multipath is not enabled fails with:

    vdsm.common.cmdutils.Error: Command ['/sbin/multipath', '-r']
    failed with rc=1 out=b'' err=b'Aug 05 05:43:11 | DM multipath
    kernel driver not loaded\\n'"

If multipath is not enabled we cannot have devices with wrong name
so there is nothing to reload, and failing the pointless command is
harmful.

This reverts commit 93944b00498d8b351b747ab31e9d298dbcdfeff2.

Change-Id: Iff748317009d7e75565b49bbe28264e387675ec0
Signed-off-by: Nir Soffer <nsoffer@redhat.com>