vm: adapt to new clientIF.notify() API
After change I08062950c3117f647944b4ff15c068853f29a463
we need to update also the calling sites to make sure to avoid

TypeError: notify() got an unexpected keyword argument '$VMID'

please note that this is not just cosmetic/noise in the logs:
it prevents VM to start.

Change-Id: I790a0e9e7a613997b5cf6bc91ca9832674d0b74d
Signed-off-by: Francesco Romani <fromani@redhat.com>