tests: fix redefinition pyflakes error
The build fails with the following error in pyflakes
version  "0.7.3-4" installed.
./tests/functional/networkTests.py:93:
      redefinition of unused 'vdsm' from line 28
./tests/functional/networkTests.py:101:
      redefinition of unused 'vdsm' from line 28
make[1]: *** [pyflakes] Error 1

Change-Id: I244dfbc031a4c10f1938d3f5a07daed757011d16
Signed-off-by: Timothy Asir Jeyasingh <tjeyasin@redhat.com>
Reviewed-on: https://gerrit.ovirt.org/41402
Continuous-Integration: Jenkins CI
Reviewed-by: Nir Soffer <nsoffer@redhat.com>
Reviewed-by: Piotr Kliczewski <piotr.kliczewski@gmail.com>
Reviewed-by: Dan Kenigsberg <danken@redhat.com>
Reviewed-on: https://gerrit.ovirt.org/42349
Tested-by: Darshan N <dnarayan@redhat.com>
Reviewed-by: Bala.FA <barumuga@redhat.com>
Continuous-Integration: Bala.FA <barumuga@redhat.com>