Revert "build: Separate 'make' targets for py27/py36 tests"
This change run in parallel:

    tox -e tests,{storage,lib,network, virt}-py27

And:

    tox -e tests,{storage,lib,network, virt}-py36

This creates a huge mess in the build log, and cause random build
failures like:

network/integration/ovs/ovs_driver_test.py ....................make[1]: *** [Makefile:1140: check] Error 245
make[1]: Leaving directory '/home/jenkins/workspace/vdsm_standard-check-patch/vdsm/tests'
ERROR: InvocationError: '/usr/bin/make -C tests check'

We cannot run tox envs in parallel without separating the build to sub
stages, running on a different machine.

This reverts commit cc7b626bd27f146239bf43c1d81d66f864567798.

Change-Id: I35366d33b5ddbb8b8ee70daad2aa58bd8a7894c9
Signed-off-by: Nir Soffer <nsoffer@redhat.com>