hsm: check volume existence in prepareImage
This patch introduces a check in prepareImage to return a consistent
error (VolumeDoesNotExist) when the volume to prepare is not found.

Before this patch the error was:

 UnboundLocalError: local variable 'leafInfo' referenced
   before assignment

Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1133617
Change-Id: Iceac3934b5eb3b7d3d68ea80ddd29cd9fe919c6c
Signed-off-by: Federico Simoncelli <fsimonce@redhat.com>
Reviewed-on: http://gerrit.ovirt.org/31937
Reviewed-by: Allon Mureinik <amureini@redhat.com>
Reviewed-by: Nir Soffer <nsoffer@redhat.com>
Reviewed-by: Dan Kenigsberg <danken@redhat.com>
(cherry picked from commit 0e9c6a4fb2f126d10d445289753abbf03ed867ae)
Reviewed-on: http://gerrit.ovirt.org/32337
Reviewed-by: Yaniv Bronhaim <ybronhei@redhat.com>