vm: hide traceback from failed qemu-ga powercycle
When we expect that the agent is not running don't log traceback from
failed qemu-ga command. Log it only for DEBUG level. This prevents
poluting logs with confusing tracebacks like:

    Traceback (most recent call last):
    File "/usr/lib/python3.6/site-packages/vdsm/virt/vm.py", line 4792, in qemuGuestAgentShutdown
        libvirt.VIR_DOMAIN_SHUTDOWN_GUEST_AGENT)
    File "/usr/lib/python3.6/site-packages/vdsm/virt/virdomain.py", line 101, in f
        ret = attr(*args, **kwargs)
    File "/usr/lib/python3.6/site-packages/vdsm/common/libvirtconnection.py", line 131, in wrapper
        ret = f(*args, **kwargs)
    File "/usr/lib/python3.6/site-packages/vdsm/common/function.py", line 94, in wrapper
        return func(inst, *args, **kwargs)
    File "/usr/lib64/python3.6/site-packages/libvirt.py", line 2685, in shutdownFlags
        if ret == -1: raise libvirtError ('virDomainShutdownFlags() failed', dom=self)
    libvirt.libvirtError: Guest agent is not responding: QEMU guest agent is not connected

Change-Id: Ie5792cfcfb9a2b68b33b074d41bf9dc7680d7ed0
Signed-off-by: Tomáš Golembiovský <tgolembi@redhat.com>