log: failure in logging
We need to reimplement log_info method since it has a bit different
signature than log method and with previous approach it fails with:

TypeError: not all arguments converted during string formatting

Change-Id: I2396d1ec98987064134af334ff0a2a4dab78d836
Signed-off-by: pkliczewski <piotr.kliczewski@gmail.com>
Reviewed-on: https://gerrit.ovirt.org/47522
Continuous-Integration: Jenkins CI
Reviewed-by: Nir Soffer <nsoffer@redhat.com>
Reviewed-by: Yaniv Bronhaim <ybronhei@redhat.com>
Reviewed-by: Dan Kenigsberg <danken@redhat.com>