vdsmapi: open pickle_path with 'rb' mode
In python 2, there's no difference between binary and text mode when
using pickle.load(f).

Since python 3 uses text mode by default, dealing with binary data
created by pickle.dump() requires specifying binary mode.
Therefore, opening pickle_path with 'rb' mode fixes the problem.

Without this change, the code fails with the following error:
UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 0:
ordinal not in range(128)

Change-Id: I873cfc339ddfa37ac91fe44aca2c00803c804802
Signed-off-by: Shani Leviim <sleviim@redhat.com>