lib: executor: handle timeout=None in __repr__
After the change 54b79818e17e44ba1acf7d47e79a7e7946b50b4f we could have
timeout=None much more often.
This exposed one bug in the __repr__ method of executor.Task if timeout
is indeed None, the format string expodes with

  File "/home/fromani/Projects/upstream/vdsm/lib/vdsm/executor.py", line 377, in __repr__
    id(self)
TypeError: %d format: a number is required, not NoneType

This patch fixes that.

Change-Id: I5960673cd97e261d7296db27dd9a1c62931989ac
Bug-Url: https://bugzilla.redhat.com/1428415
Backport-To: 4.1
Signed-off-by: Francesco Romani <fromani@redhat.com>