tests, storage: Add test for full slots case in HSM mailbox
Current test exposes incapability of HSM mailer to handle more
than (MESSAGES_PER_MAILBOX - 1 = 62) messages, due to a bug fixed
in the next patch.

This raises a worker thread exception:

Traceback (most recent call last):
  File "vdsm/lib/vdsm/storage/mailbox.py", line 473, in _run
    self._handleMessage(message)
  File "vdsm/lib/vdsm/storage/mailbox.py", line 411, in _handleMessage
    raise RuntimeError("HSM_MailMonitor - Active messages list full, "
RuntimeError: HSM_MailMonitor - Active messages list full, cannot add new message

So in this patch the test is marked as xfail, to be fixed in next patch.

Change-Id: Id12797e366a3a1c8059b4eb6360f92bb2920f4bd
Signed-off-by: Amit Bawer <abawer@redhat.com>