rawhide: Skip blivet tests on Fedora rawhide
Importing blivet fail with:

    ValueError: Namespace BlockDev not available for version 1.0

Marking the import test as xfail, and updating the import check in the
test using blivet to handle the ValueError.

To skip the tests only on rawhide, we use vdsm.osinfo.version(), so we
require now the rpm-python package.

Change-Id: I050475289756649d4ae58af08f405ffaef6f8d30
Signed-off-by: Nir Soffer <nsoffer@redhat.com>