tests: fix integration tests
This patch fixes an issue with integration tests which are not part of
general build process, getting the following error:
AttributeError: '_DummyBridge' object has no attribute 'dispatch'
We use to use __getattr__ method but we replaced
it with dispatch not to swap '.' with '_'.

Related-To: https://gerrit.ovirt.org/53472
Change-Id: I98dfe4c863b2780f7d28b62a857e2fffa5f40acd
Signed-off-by: pkliczewski <piotr.kliczewski@gmail.com>