py3: Get domain keys as a static list instead of an iterator
Fix AttributeError: 'dict_keys' object has no attribute 'remove'

Change-Id: I4aaad8a0df045d5f5a942e44b9dfb26e0f8d54ad
Signed-off-by: Amit Bawer <abawer@redhat.com>