tests: Skip performance tests on CI
The test takes 0.1 seconds on my laptop, but on Jenkins it sometimes
take 1.2 seconds and fail the test:

     # This takes 0.065 seconds on my laptop, 1 second should be enough even
     # on overloaded jenkins slave.
     self.assertTrue(elapsed < 1.0, "Elapsed time: %f seconds" % elapsed)
     AssertionError: Elapsed time: 1.193098 seconds

Skip this test on CI, and lower the minimal time to catch earlier
performance regressions in this area.

Change-Id: I42771edd8a1e3e9c64ace4321b2861880efcf6a7
Signed-off-by: Nir Soffer <nsoffer@redhat.com>