client: do not protect requests on client side
We need to keep message content without any changes before sending it to
the server. If we won't json parser fails with:

TypeError: '********' is not JSON serializable


Change-Id: I197591fbf0fb42647267b6901998324dd02a8080
Signed-off-by: pkliczewski <piotr.kliczewski@gmail.com>
Reviewed-on: https://gerrit.ovirt.org/56288
Continuous-Integration: Jenkins CI
Reviewed-by: Nir Soffer <nsoffer@redhat.com>
Tested-by: Simone Tiraboschi <stirabos@redhat.com>
Reviewed-by: Yaniv Bronhaim <ybronhei@redhat.com>