tox.ini: add dep on packaging in tox
There is an incompatibility between packaging version from CentOS and
setuptools from pip. Which causes a failure running the tests:
TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'

See also https://github.com/pypa/setuptools/issues/4483

Fix this by using a the current packaging version instead of the CentOS
packaged one.

Signed-off-by: Jean-Louis Dupond <jean-louis@dupond.be>