sampling: return correct vcpu positioning info
In commit 262917767771ef590fad2a4266dad1c2a915e5ba
We incorrectly started to report the full vcpu()
output from libvirt. numaUtils code expects
a subset of this data, so when NUMA is enabled
(e.g. always for the hotplugMem feature), we
start to spam the logs with

File "/usr/share/vdsm/numaUtils.py", line 106, in
getVmNumaNodeRuntimeInfo
    _get_vcpu_positioning(vm))
  File "/usr/share/vdsm/numaUtils.py", line 141, in
_get_mapping_vcpu_to_pcpu
    for (vcpu_id, _, _, pcpu_id) in infos:
ValueError: need more than 1 value to unpack

Every 15s, and we broke the numa sampling.

This patch restores the correct behaviour.

Change-Id: Ic28dbbef45c20c32f8b72b0c4d91fe2e75700d2a
Signed-off-by: Francesco Romani <fromani@redhat.com>
Reviewed-on: https://gerrit.ovirt.org/42571
Continuous-Integration: Jenkins CI
Reviewed-by: Piotr Kliczewski <piotr.kliczewski@gmail.com>
Reviewed-by: Dan Kenigsberg <danken@redhat.com>