lvm: Log detailed warning if reloading failed
Previously we logged nothing if "vgs" failed. The only clue that "vgs"
failed is this failure to access a VG attribute later:

      File "/usr/lib/python2.7/site-packages/vdsm/storage/lvm.py", line 1224, in extendLV
        extent_size = int(vg.extent_size)
      File "/usr/lib/python2.7/site-packages/vdsm/storage/lvm.py", line 82, in __getattr__
        raise AttributeError("Failed reload: %s" % self.name)
    AttributeError: Failed reload: f1168ddf-917c-4ef4-b553-e034ee2983ec

The original error from the failed "vgs" command was lost.

Add detailed warning log when "vgs" fails, and add more details in the
warning for "lvs" failure.

Here is example warning when vgs fails:

2018-10-07 12:12:39,211-0400 WARN (jsonrpc/7) [storage.LVM] Reloading
VGs failed (vgs=[u'840d159f-3a01-40d6-943a-ce4ed7a63960'] rc=5 out=[]
err=['  Volume group "840d159f-3a01-40d6-943a-ce4ed7a63960" not found',
'  Cannot process volume group 840d159f-3a01-40d6-943a-ce4ed7a63960'])
(lvm:377)

This change adds bogus warning about missing VG when creating storage
domain. Unfortunately we cannot avoid this with the current way the
system works.

Change-Id: I984ecdc2e8cecec9e45ec91cd1a99423481c6ea7
Bug-Url: https://bugzilla.redhat.com/1553133
Signed-off-by: Nir Soffer <nsoffer@redhat.com>