tests: Fix FakeClientIF interface
clientIF was missing the "ready" property, which caused random failures
on jenkinks:

    AttributeError: FakeClientIf instance has no attribute 'ready'

Change-Id: I3b26f5c9373e92a7de3bbbc2f4ed682dce70b92d
Signed-off-by: Nir Soffer <nsoffer@redhat.com>
Reviewed-on: http://gerrit.ovirt.org/28771
Reviewed-by: Piotr Kliczewski <piotr.kliczewski@gmail.com>
Reviewed-by: Dan Kenigsberg <danken@redhat.com>