fix can't get ssl opt in vdsm sos plugin
when execute sosreport will get exception as below:

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sos/sosreport.py",
line 693, in sosreport
    plug.setup()
  File "/usr/lib/python2.7/site-packages/sos/plugins/vdsm.py",
line 82, in setup
    sslopt = ['', '-s '][config.getboolean('vars', 'ssl')]
NoOptionError: No option 'ssl' in section: 'vars'
  Running plugins. Please wait ...

* import vdsm.config to plugin for using default value.
* because can not import vdsm module when the plugin's name same with it.
so add hack function for import vdsm python lib.

Change-Id: Icbbc9a10202f191d0754bfae5c3f876b6c53a560
Signed-off-by: Xu He Jie <xuhj@linux.vnet.ibm.com>
Reviewed-on: http://gerrit.ovirt.org/4349
Reviewed-by: Dan Kenigsberg <danken@redhat.com>
Tested-by: Dan Kenigsberg <danken@redhat.com>