vm: conf: proper locking in status()
We are still getting the error
RuntimeError: dictionary changed size during iteration

When calling Vm.status(), especially during migrations,
so we must review our usage of Vm.conf and ensure the lock
is always used.

Change-Id: I397562bb94c8b696a0b34484907e7d489a800878
Bug-Url: https://bugzilla.redhat.com/1318550
Signed-off-by: Francesco Romani <fromani@redhat.com>
Reviewed-on: https://gerrit.ovirt.org/54906
Reviewed-by: Dan Kenigsberg <danken@redhat.com>
Continuous-Integration: Jenkins CI