tests: network: remove useless monkeypatch
libvirtconnection_test.py started to fail regularly on my F27
box with errors like:

TypeError: __init__() got an unexpected keyword argument 'killOnFailure'

or

TypeError: nodeDeviceLookupByName() takes exactly 2 arguments (1 given)

simplest reproducer:

./run_test_local.sh network/tc_test.py common/libvirtconnection_test.py

the root cause is still unclear, but do we stil need to monkeyclass
tc_test.py in the first place?

This patch removes the apparently useless monkeypatching, fixing
the issue by side effect.

Change-Id: Ie6d3ca4b4f7d5a568fee20c3a1b3a0ff188b3491
Signed-off-by: Francesco Romani <fromani@redhat.com>