check_imports: fix expected to fail
expected_to_fail should be initialized to an empty set, since
it used to be a set and not a dict.
This caused travis fedora rawhide builds to fail:

check_imports.py:43: in find_modules
    expected_to_fail.add("vdsm.gluster.storagedev")
E   AttributeError: 'dict' object has no attribute 'add'

Change-Id: I25dee64178e9ab47ab63207c21adbdb98be2abbc
Signed-off-by: Irit Goihman <igoihman@redhat.com>