exception: Add context to some virt errors
Change NoSuchVM and MigrationInProgress to inherit from
ContextException, so we can raise these errors with context in new code
for plugging and unplugging leases.

Nobody is raising these errors yet, since virt code is still using the
define module, using same instance of the exception for all errors.

Change-Id: I32ec3f86f8d53f8412f4c0526fc85e2a42e30ea5
Bug-Url: https://bugzilla.redhat.com/1408825
Signed-off-by: Nir Soffer <nsoffer@redhat.com>