vm: conf: proper locking in migration path
We are still getting the error
RuntimeError: dictionary changed size during iteration

When calling Vm.status(), especially during migrations,
so we must review our usage of Vm.conf and ensure the lock
is always used.

Change-Id: Ic943e4af2f444f8ffe167175e40a9a2f28afc344
Bug-Url: https://bugzilla.redhat.com/1318550
Signed-off-by: Francesco Romani <fromani@redhat.com>
Reviewed-on: https://gerrit.ovirt.org/54905
Reviewed-by: Dan Kenigsberg <danken@redhat.com>
Continuous-Integration: Jenkins CI