tests: unbreak `make rpm'
The commit b957535 broke `make rpm'.
We need to ship the `tests_child.py' helper, otherwise we see the
sigutils tests fail like

  File "vdsm-4.18.0/tests/sigutils_test.py", line 108, in test_register_twice
    with child_test('check_register_twice') as child:
  File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "vdsm-4.18.0/tests/sigutils_test.py", line 51, in child_test
    cwd=os.path.dirname(__file__)
  File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1335, in
_execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Verified on Fedora 23 and Centos 7.x

Change-Id: I789b8ea1cec5b20dd850768ad3c612a0907598eb
Signed-off-by: Francesco Romani <fromani@redhat.com>
Reviewed-on: https://gerrit.ovirt.org/58019
Reviewed-by: Nir Soffer <nsoffer@redhat.com>
Reviewed-by: Irit Goihman <igoihman@redhat.com>
Reviewed-by: Yaniv Bronhaim <ybronhei@redhat.com>
Continuous-Integration: Dan Kenigsberg <danken@redhat.com>