gluster: fix TypeError in exception.py
Currently gluster cli functions throws error in exception due to a bug
in python multiprocess http://bugs.python.org/issue15440 which fails
to re-raise in supervdsm side.  This is workaround fix to set optional
arguments to constructor of VdsmException and GlusterException

Traceback (most recent call last):
  File "/usr/share/vdsm/rpc/BindingXMLRPC.py", line 1136, in wrapper
    res = f(*args, **kwargs)
  File "/usr/share/vdsm/gluster/api.py", line 80, in wrapper
    rv = func(*args, **kwargs)
  File "/usr/share/vdsm/gluster/api.py", line 686, in createBrick
    raidParams)
  File "/usr/share/vdsm/supervdsm.py", line 50, in __call__
    return callMethod()
  File "/usr/share/vdsm/supervdsm.py", line 48, in <lambda>
    **kwargs)
  File "<string>", line 2, in glusterCreateBrick
  File "/usr/lib64/python2.6/multiprocessing/managers.py", line 726, in _callmethod
    kind, result = conn.recv()
TypeError: ('__init__() takes exactly 2 arguments (1 given)',
    <class 'gluster.exception.GlusterHostStorageDeviceInUseException'>, ())

Change-Id: I9a0622baf0e2fcba810f9ef3e36a1ea8b95b61c4
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1231722
Signed-off-by: Timothy Asir Jeyasingh <tjeyasin@redhat.com>
Reviewed-on: https://gerrit.ovirt.org/45001
Reviewed-by: Ramesh N <rnachimu@redhat.com>
Reviewed-by: Dan Kenigsberg <danken@redhat.com>
Continuous-Integration: Dan Kenigsberg <danken@redhat.com>