exception: Make VdsmException reusable
VdsmException was initializing code and message to default values if
called without arguments. This make is useless as as base class for
more specific exceptions, defining real code and message.

GlusterException, the only exception inheriting from VdsmException,
avoided this issue by overriding __init__.

Required-For: https://bugzilla.redhat.com/1295778
Change-Id: Icd6643d9670cb9b067e372bf5a1a6c57ced41954
Signed-off-by: Nir Soffer <nsoffer@redhat.com>
Reviewed-on: https://gerrit.ovirt.org/48875
Reviewed-by: Francesco Romani <fromani@redhat.com>
Reviewed-by: Piotr Kliczewski <piotr.kliczewski@gmail.com>
Continuous-Integration: Jenkins CI
Reviewed-on: https://gerrit.ovirt.org/52982
Tested-by: Piotr Kliczewski <piotr.kliczewski@gmail.com>
Reviewed-by: Yaniv Bronhaim <ybronhei@redhat.com>
Reviewed-on: https://gerrit.ovirt.org/53698
Continuous-Integration: Francesco Romani <fromani@redhat.com>