vm: conf: proper locking in onConnect()
We are still getting the error
RuntimeError: dictionary changed size during iteration

When calling Vm.status(), especially during migrations,
so we must review our usage of Vm.conf and ensure the lock
is always used.

Change-Id: I5f75630e204708bb4352f68240550b2b454806cc
Bug-Url: https://bugzilla.redhat.com/1318550
Signed-off-by: Francesco Romani <fromani@redhat.com>
Reviewed-on: https://gerrit.ovirt.org/54907
Reviewed-by: Dan Kenigsberg <danken@redhat.com>
Continuous-Integration: Jenkins CI