vmxml: separate vmxml.Element and etree.Element
Up until now, the vmxml.Element was quite liberal in accepting
arguments to its append*() methods; same was true for
vmxml.append_child.
We had freedom to mix and match vmxml.Element and etree.Elements
freely, without any apparent harm.

Things change in python3; if we run the very same code under python3,
for example because of the tests introduced in
patch Id1beb214e76c5173de318406fc6208990d33adbb
we get errors like

  File "lib/vdsm/virt/vmxml.py", line 334, in appendChild
    self._elem.append(element)
TypeError: append() argument must be xml.etree.ElementTree.Element, not Element

To fix this issue, we must always append etree Elements childs.
Confusion can arise from a couple od sources; we add a special-purpose
appendEtree method to mark such places, in order to always append
the right element.

Change-Id: I60003e69702508e173703fcfa7d5ec2e0cffbd14
Signed-off-by: Francesco Romani <fromani@redhat.com>