Fix schema
Current schema is presenting the build error:

 ValueError: 'HostDeviceParams' comment mentions 'physfn' which is not defined

This patch is adding the missing 'physfn'.

Change-Id: I28964143ae861d0c6237f648f11a0b27acc432f2
Signed-off-by: Amador Pahim <apahim@redhat.com>
Reviewed-on: http://gerrit.ovirt.org/36427
Reviewed-by: Dan Kenigsberg <danken@redhat.com>