_addNetwork: never try to set mtu=None to an existing bridge
On my EL6 host I tried to configure the 'ovirtmgmt' network manually, so it
becomes a libvirt network (and in this case I would be able to reproduce
a case when a gateway is duplicated by our dynamic source route thread).

  vdsClient -s 0 setupNetworks 'networks={ovirtmgmt:{nic:eth0,bootproto:dhcp}}'

The command failed, however (Unexpected exception):

  MainProcess|Thread-1000::INFO::2015-02-18 10:55:08,731::api::304::root::(_addNetwork) Adding network ovirtmgmt with vlan=None, bonding=None, nics=[u'eth0'], bondingOptions=None, mtu=None, bridged=True, defaultRoute=True,options={u'bootproto': u'dhcp', 'implicitBonding': True}

  MainProcess|Thread-1000::DEBUG::2015-02-18 10:55:08,732::ifcfg::460::root::(_persistentBackup) backing up ifcfg-ovirtmgmt: DEVICE=ovirtmgmt
  ONBOOT=yes
  TYPE=Bridge
  DELAY=0
  STP=off
  BOOTPROTO=dhcp
  MTU=1500
  DEFROUTE=yes
  NM_CONTROLLED=no
  HOTPLUG=no

  MainProcess|Thread-1000::DEBUG::2015-02-18 10:55:08,733::utils::623::root::(execCmd) /sbin/ip link set dev eth0 mtu None (cwd None)
  MainProcess|Thread-1000::DEBUG::2015-02-18 10:55:08,738::utils::643::root::(execCmd) FAILED: <err> = 'Error: argument "None" is wrong: Invalid "mtu" value\n\n'; <rc> = 255

  MainProcess|Thread-1000::ERROR::2015-02-18 10:55:14,507::supervdsmServer::108::SuperVdsm.ServerCallback::(wrapper) Error in setupNetworks
  Traceback (most recent call last):
    File "/usr/share/vdsm/supervdsmServer", line 106, in wrapper
      res = func(*args, **kwargs)
    File "/usr/share/vdsm/supervdsmServer", line 203, in setupNetworks
      return setupNetworks(networks, bondings, **options)
    File "/usr/share/vdsm/network/api.py", line 855, in setupNetworks
      logger, _netinfo)
    File "/usr/share/vdsm/network/api.py", line 690, in _add_missing_networks
      implicitBonding=True, _netinfo=_netinfo, **d)
    File "/usr/share/vdsm/network/api.py", line 225, in wrapped
      ret = func(**attrs)
    File "/usr/share/vdsm/network/api.py", line 328, in _addNetwork
      _update_bridge_ports_mtu(net_ent.name, mtu)
    File "/usr/share/vdsm/network/api.py", line 246, in _update_bridge_ports_mtu
      ipwrapper.linkSet(port, ['mtu', str(mtu)])
    File "/usr/lib/python2.6/site-packages/vdsm/ipwrapper.py", line 630, in linkSet
      _execCmd(command)
    File "/usr/lib/python2.6/site-packages/vdsm/ipwrapper.py", line 525, in _execCmd
      raise IPRoute2Error(error)
  IPRoute2Error: ['Error: argument "None" is wrong: Invalid "mtu" value', '']

Change-Id: Ie92c2257078b7b5971cfc94393d6ad3a8db59850
Signed-off-by: Ondřej Svoboda <osvoboda@redhat.com>
Reviewed-on: https://gerrit.ovirt.org/37899
Reviewed-by: Petr Horáček <phoracek@redhat.com>
Reviewed-by: Ido Barkan <ibarkan@redhat.com>
Reviewed-by: Dan Kenigsberg <danken@redhat.com>