exception: Fix bad error code
A comma sneaked after the error code, making the error code a tuple
instead of int.

The error was introduced in commit e84aaadc3c9e (exception: Add
exceptions for vdsm.define errors).

Change-Id: I2ffd86997c6bf7ef55f58eed8bf37315501f3b87
Signed-off-by: Nir Soffer <nsoffer@redhat.com>
Reviewed-on: https://gerrit.ovirt.org/66443
Continuous-Integration: Jenkins CI
Reviewed-by: Dan Kenigsberg <danken@redhat.com>