tests: improve faking
This patch avoids this error due to insufficient faking
AttributeError: 'NoneType' object has no attribute 'notify'

Change-Id: Idee9d3fa1aa9b809a65b04b7972f70d6af848a0c
Signed-off-by: Francesco Romani <fromani@redhat.com>