storage: avoid undefined variable when connectin list is empty
When connecting or disconnecting storage server, current code assumes
that connection list sent by engine is never empty. However, this is not
the case and when there are two or more iSCSI SDs which use same iSCSI
target, engine sends empty connection list when requesting disconnect,
see BZ #2054745 [1] for more details. In such case current code fails
with

    UnboundLocalError: local variable 'con_info' referenced before assignment

which is bad in any case. Avoid using potentially undefied variable.

Better handling of empty connection list will be improved in follow-up
patch.

[1] https://bugzilla.redhat.com/2054745

Change-Id: I1a4a5d068ff75669d3ceafee1cc427213a552538
Signed-off-by: Vojtech Juranek <vjuranek@redhat.com>