pylint: Rewrite readSessionInfo eliminating pylint errors
When reading iscsi session, we used to dynamically create a list of
values read from sysfs, and unpack them into local variables. This code
made pylint unhappy, was hard to follow, and error prone. Eliminate the
bad code using the new sysfs module.

Error handling is improved now when reading integer values. Previously
if port or tpgt were missing, we failed with:

    ValueError: invalid literal for int() with base 10: ''

Now we will fail a clear error about the missing attribute:

    IOError: [Errno 2] No such file or directory: '.../persistent_port'

Security is improved by using sysfs.read_password, the raw password is
never stored in a local variable, so there is no chance to log it by
mistake.

Change-Id: Icdf7a214d809c2dfa9125dd66f78f51bcd53f882
Signed-off-by: Nir Soffer <nsoffer@redhat.com>