virt: Fix handling of improbable allocation size
If qemu reports improbable allocation value, we pause the vm to prevent
corruption. Unfortunately, just before pausing the vm, we attempt to log
an error with list of arguments instead of a string, and crash before
pausing the vm:

    TypeError: not all arguments converted during string formatting

Now we log the error message and pause the vm.

Change-Id: I29364f653e9d5549f40c2708c2f39801268ac010
Signed-off-by: Nir Soffer <nsoffer@redhat.com>
Reviewed-on: https://gerrit.ovirt.org/38049
Reviewed-by: Francesco Romani <fromani@redhat.com>
Reviewed-by: Adam Litke <alitke@redhat.com>