vm: added missing diskReplicate slot in Drive class
Following commit I6e8dadabdd02d3b44606f215c4bc7b7e306a591a,
added missing 'diskReplicate' slot in VM -> Drive class.

Currently, live storage migration fails due to an exception [1]
on 'diskReplicateStart' method.

[1] AttributeError: 'Drive' object has no attribute 'diskReplicate'

Change-Id: Iffd1e8605786c41920f5c5f171e42fb9a12474dc
Signed-off-by: Daniel Erez <derez@redhat.com>
Reviewed-on: http://gerrit.ovirt.org/28131
Reviewed-by: Nir Soffer <nsoffer@redhat.com>
Reviewed-by: Dan Kenigsberg <danken@redhat.com>
Reviewed-by: Francesco Romani <fromani@redhat.com>
Reviewed-by: Martin Polednik <mpoledni@redhat.com>