blockVolume: parse slot into an int
Before commit 6612cd40432f5864976fc5c6129031d64779a1f1,
the 'slot' parameter was parsed as an int.
Currently, it parsed as a string, which may cause an error:
TypeError: unsupported operand type(s) for +: 'int' and 'str'.

Change-Id: Ia1238f0995a36eff976d588be60909fc0113bc19
Bug-Url: https://bugzilla.redhat.com/1836609
Signed-off-by: Shani Leviim <sleviim@redhat.com>