fileUtils: Fix error handling and logging in tarCopy
When fileUtils.tarCopy() failed, we get unhelpful error:

    vdsm.storage.fileUtils.TarCopyFailed: (1, 0, b'', b'')

This tuple (1, 0, b'', b'') means that the reader child process failed
with rc=1, and the writer child process terminated normally with rc=0.
However, the rest of the arguments are the empty stdout and stderr of
the successful writer child process. The useful stderr of the failing
reader child process is dropped.

Fix error handling so we collect stderr from both reader and writer
child processes, and on error we raise a detailed exception all failing
child processes.

Add debug logs when starting the commands and when both child processes
terminate, so we can find code writing to the master filesystem after
the reader was started.

Add info log since copying the master filesystem modifies the target,
and we log as system state changes in info level.

On errors we raise now a new public error instead of a private error, so
the detailed error will propagate to engine log.

Here is an example error when both reader and writer child
processes failed (reformatted to shorten long lines):

vdsm.storage.exception.TarCommandError: Tar command failed: (
{'reader': {'cmd': ['/usr/bin/tar', 'cf', '-', '-C', '/src', '.'],
'rc': 2, 'err': '/usr/bin/tar: /src: Cannot open: No such file or directory\n'
'/usr/bin/tar: Error is not recoverable: exiting now\n'},
'writer': {'cmd': ['/usr/bin/tar', 'xf', '-', '-C', '/dst', '--touch'],
'rc': 2, 'err': '/usr/bin/tar: This does not look like a tar archive\n'
'/usr/bin/tar: Exiting with failure status due to previous errors\n'}},)

Change-Id: Ib97c66bf9abe12d984c40283a29d07fc5c9c3e09
Bug-Url: https://bugzilla.redhat.com/1913764
Signed-off-by: Nir Soffer <nsoffer@redhat.com>