tests: checkSudo should skip if bin/sudo is missing
If the unit tests are run with no sudo binary installed,

    OSError: [Errno 2] No such file or directory

is raised instead of the test being skipped.

Change-Id: I448f14e8cee54edb5367b575fa36dc6f14b934aa
Signed-off-by: Dan Kenigsberg <danken@redhat.com>
Reviewed-on: http://gerrit.ovirt.org/31966
Reviewed-by: Michal Skrivanek <michal.skrivanek@redhat.com>
Reviewed-by: Yaniv Bronhaim <ybronhei@redhat.com>