fixed a key error in _delNetwork
When _delNetwork was called from _delBrokenNetwork its netinfo
is adapted so it would be able to remove the broken netwrok.
Without this patch, trying to remove a broken bridgeless network fails
With a KeyError due to a missing bootproto element.

Traceback (most recent call last):
  File "/usr/share/vdsm/supervdsmServer", line 100, in wrapper
    res = func(*args, **kwargs)
  File "/usr/share/vdsm/supervdsmServer", line 200, in setupNetworks
    return setupNetworks(networks, bondings, **options)
  File "/usr/share/vdsm/network/api.py", line 798, in setupNetworks
    configurator=configurator)
  File "/usr/share/vdsm/network/api.py", line 404, in _delBrokenNetwork
    implicitBonding=False, _netinfo=_netinfo)
  File "/usr/share/vdsm/network/api.py", line 223, in wrapped
    ret = func(**attrs)
  File "/usr/share/vdsm/network/api.py", line 462, in _delNetwork
    net_ent.ip.bootproto = _netinfo.networks[network]['bootproto4']
KeyError: 'bootproto4

This was introduced by commit 1886113ee096f2d414738be0c5b11ca5079a5a3c
and should/shouldnot be backported to the stable branch.

Change-Id: I09d32946cf2667b1888b1d84d0eab2d7118a42b0
Signed-off-by: Ido Barkan <ibarkan@redhat.com>
Reviewed-on: http://gerrit.ovirt.org/36598
Reviewed-by: Dan Kenigsberg <danken@redhat.com>