tests: Use monotonic_time for time sensitive test
The concurrency test fails randomly taking extremly long time:

FAIL: test_concurrency (common.concurrent_test.TMapTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/workspace/vdsm_standard-check-patch/vdsm/tests/common/concurrent_test.py", line 215, in test_concurrency
    self.assertLess(elapsed, 1.0)
AssertionError: 3.9155890941619873 not less than 1.0

In the past I assumed that this is an issue with overloaded slave, but
the failure does not match the test log:

First thread started at:
2019-02-06 21:48:41,783

Last thread stopped at:
2019-02-06 21:48:42,302

So it looks like the threads did finish in (302 + 217) 519 milliseconds.

How did we get runtime of 3.9 seconds?

I cannot explain this, but lets replace time.time() with vdsm
monotonic_time() which has lower resolution, but should be more
reliable.

Change-Id: I4fd8636ec34389ef998e1b0220a96473dc26df21
Signed-off-by: Nir Soffer <nsoffer@redhat.com>