py3: drop vmmigration and vmrecovery from blacklist
Python 3 was unhappy by vmfakelib's usage of lambda as bound methods as
done by MonkeyPatch, exploding with the likes of

Traceback (most recent call last):
  File "vdsm.git/tests/testlib.py", line 143, in wrapper
    return f(self, *args)
  File "vdsm.git/tests/vmmigration_test.py", line 271, in test_migrate_from_status
    res = testvm.migrate({})  # no params needed
  File "<decorator-gen-3>", line 2, in migrate
  File "vdsm.git/lib/vdsm/common/api.py", line 94, in method
    return func(*args, **kwargs)
  File "vdsm.git/lib/vdsm/virt/vm.py", line 1919, in migrate
    self.send_status_event()
TypeError: <lambda>() missing 1 required positional argument: '_'

This patch places these assignements directly in the mocked Vm object.
Minor tweaks were applied to recovery.py and vm.py in order to make the
tests pass.
Finally the dropped tesst modules can be moved to virttests, where they
belong.

Change-Id: I7dff7e0d6886d695c61a42781f7dda73e8002a29
Signed-off-by: Dan Kenigsberg <danken@redhat.com>