tests: Require pytest 4.0
Some interesting features since 3.3:
- monkeypatch.context() - for localized monkey patching
- colored progress dots

And tons of bug fixes and other features:
https://github.com/pytest-dev/pytest/blob/master/CHANGELOG.rst

We had to backport this patch in order to avoid a CI error

    pluggy.PluginValidationError: Plugin 'pytest_cov' could not be loaded:
    (pytest 3.3.0, Requirement.parse('pytest>=3.6'))!

Change-Id: Ife4d7641ac3786d308b6b116aea6fd863ee8d230
Signed-off-by: Nir Soffer <nsoffer@redhat.com>
Signed-off-by: Dan Kenigsberg <danken@redhat.com>