tests: Hide errors when testing noisy code
configurator.remove_config try to remove all configurations even if some
configurators fail, so it writes errors to stderr and continue. This
behavior makes sense, but breaks tests progress display:

    test_remove_config                                          can't remove configuration of module a
Traceback (most recent call last):
  File "/home/nsoffer/src/vdsm/lib/vdsm/tool/configurator.py", line 236, in remove_config
    _removeConf(c)
  File "/home/nsoffer/src/vdsm/lib/vdsm/tool/configurator.py", line 120, in _removeConf
    getattr(module, 'removeConf', lambda: None)()
  File "/home/nsoffer/src/vdsm/tests/toolTests.py", line 75, in removeConf
    raise Exception('mock invalid remove conf')
Exception: mock invalid remove conf
OK

Now we redirect stderr to stdout during this test, so the output is more
pleasing:

    test_remove_config                                          OK

Change-Id: I4d1bb16e0aabc9f4e2bb0ca88bc7ce4cd189e24d
Signed-off-by: Nir Soffer <nsoffer@redhat.com>
Reviewed-on: https://gerrit.ovirt.org/41365
Continuous-Integration: Jenkins CI
Reviewed-by: Yaniv Bronhaim <ybronhei@redhat.com>
Reviewed-by: mooli tayer <mtayer@redhat.com>
Reviewed-by: Dan Kenigsberg <danken@redhat.com>