yajsonrpc: Fix python 3.6 compatibility
Python 3.6 changed json.loads() to use keyword only arguments, breaking
some calls in yajsonrpc. Fix the calls to use keyword style.

The tests are failing on python 3.6 since commit 464a1d6f96cb (rpc:
propagate executor issue to the engine) with this error:

    Traceback (most recent call last):
      File "/vdsm/lib/yajsonrpc/__init__.py", line 107, in decode
        obj = json.loads(msg, 'utf-8')
    TypeError: loads() takes 1 positional argument but 2 were given

See https://www.python.org/dev/peps/pep-3102/

Change-Id: Ia3a35bc4d61f8edfe36c6142971722bb603c351f
Signed-off-by: Nir Soffer <nsoffer@redhat.com>