task: Fix wrong import during recovery
During task recovery, task try to import a module name, failing with:

2017-07-16 18:49:11,395+0300 ERROR (tasks/9) [storage.TaskManager.Task]
(Task='8e3b5318-2b14-450d-bcb2-a6caf841b142') Unexpected error
(task:870) Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/vdsm/storage/task.py", line 877, in _run
    return fn(*args, **kargs)
  File "/usr/lib/python2.7/site-packages/vdsm/storage/task.py", line 398, in run
    [self.moduleName])
ImportError: No module named storage.volume

This is expected since there is no module name storage.volume. All
storage modules moved recently to vdsm.storage. Fix the import path to
use the correct fully qualified module name.

Change-Id: I6aa32aafeea52fa98968c7df67237cc91322f5a3
Bug-Url: https://bugzilla.redhat.com/1472253
Signed-off-by: Nir Soffer <nsoffer@redhat.com>