gluster: Fix exception string
Since commit 7e3b904df052 (gluster: Fix errors related to heal info
command) we raise both strings and list of lines. But GlusterException
is expecting only list of lines, formatting messages like:

GlusterCmdExecFailedException: Command execution failed
error: E
r
r
o
r

:

R
e
q
u
e
s
t

t
i
m
e
d

o
u
t

Replace the complex code formatting multi line exception message with
simpler single line format, matching other exceptions in vdsm.

Change-Id: I9d5bf7ec2d1116c71966088370e0860d5cb81e51
Signed-off-by: Nir Soffer <nsoffer@redhat.com>