vdsClient: Fix str/unicode concatenation issue.
"vdsClient -s 0 getVmsInfo <spUUID>" command fails with error:
Error using command: 'ascii' codec can't encode characters in position
2001-2004: ordinal not in range(128)

Here the snip from guest info xml causing the issue:
...
<app_list>Windows XP ¸üÐÂ (KB898461),Microsoft Kernel-Mode Driver Framework
Feature Pack 1.9,RHEV-Tools 3.2.8,WebFldrs XP,RHEV-Serial 3.2.4,RHEV-Spice-Agent
3.2.5,RHEV-Agent 3.2.5,RHEV-SSO 3.2.4,RHEV-USB 3.2.3,RHEV-Balloon 3.2.4,
RHEV-Spice 3.2.3,RHEV-Block 3.2.4,RHEV-Network 3.2.4</app_list>
...

Positions 2001-2004 point for characters "¸üÐÂ".

infos['vmlist'][entry] can be type str or unicode. When it happens to
be unicode with characters out of ASC-II range, converted to str and
concatenated with the given strings, the issue is triggered:

To reproduce with python interpreter:

>>> var = u'¸üÐÂ'
>>> type(var)
<type 'unicode'>
>>> test = 'string' + str(var)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal
not in range(128)

This patch is removing the str() conversion for infos['vmlist'][entry]. The result
is 'message' variable as type unicode when infos['vmlist'][entry] is unicode.

Also, to avoid stdout redir encode error, the messages print is encoded as UTF-8.

Change-Id: I44dce25bb167da8ade579b2d67eb34a0e05f491b
Signed-off-by: Amador Pahim <apahim@redhat.com>
Reviewed-on: http://gerrit.ovirt.org/19032
Reviewed-by: Ayal Baron <abaron@redhat.com>
Reviewed-by: Dan Kenigsberg <danken@redhat.com>