add helper script for running storage test env
Getting a container test environment is currently not straight forward.

Add a helper script which starts a container from existing image used
in CI, similar to what travis uses.

Currently the root permissions are unfortunately required in order to
set correct labels on /run/udev, runnning as regular user fails with:

Error: failed to set file label on /run/udev: operation not permitted

Tested with: podman-3.0.1-7.module+el8.4.0+11311+9da8acfb.x86_64

Signed-off-by: Roman Bednar <rbednar@redhat.com>
Change-Id: I3b8ac7d53d131329d660a4cf99def67286b5e105