vmstats: Fix cpu usage key names
Since commit 9ba66c903083e (virt: Additional reporting of CPU usage in
ns) we are accessing the wrong keys, filling the logs with:

    Traceback (most recent call last):
      File "/usr/share/vdsm/virt/vm.py", line 1338, in _getRunningVmStats
        vm_sample.interval)
      File "/usr/share/vdsm/virt/vmstats.py", line 37, in produce
        cpu(stats, first_sample, last_sample, interval)
      File "/usr/share/vdsm/virt/vmstats.py", line 78, in cpu
        stats['cpuUsage'] = str(last_sample['system_time']
    KeyError: 'system_time'

Now we check the correct keys, and do this inside the try block handling
missing keys, so errors are reported in a consistent way.

Change-Id: Id26c427d67de47cbcc39ddd43ab4cfe8467432c4
Signed-off-by: Nir Soffer <nsoffer@redhat.com>
Reviewed-on: https://gerrit.ovirt.org/40845
Continuous-Integration: Jenkins CI
Reviewed-by: Francesco Romani <fromani@redhat.com>
Reviewed-by: Piotr Kliczewski <piotr.kliczewski@gmail.com>
Reviewed-by: Dan Kenigsberg <danken@redhat.com>
Tested-by: Piotr Kliczewski <piotr.kliczewski@gmail.com>