tcTests: add verbosity to addBridge failure
All too often recently, testUtf8BridgeEthtoolDrvinfo (and others) fail
with

    CalledProcessError: Command '['/usr/sbin/brctl', 'addbr', 'vdsmtest-ME5LU']' returned non-zero exit status 1

when run by Jenkins.

This patch includes the stdout and stderr of the failing command so we
can understand the issue better, and fix it or skip it.

Change-Id: I83cdf07ccbf82ef27527d358a96892058fc597fc
Signed-off-by: Dan Kenigsberg <danken@redhat.com>
Reviewed-on: https://gerrit.ovirt.org/40910
Continuous-Integration: Jenkins CI
Reviewed-by: Ido Barkan <ibarkan@redhat.com>
Reviewed-by: Francesco Romani <fromani@redhat.com>