storage_connection: unexpected keyword 'timeout'
remove from mount.Mount() timeout argument
added to umount() and mount() the timeout argument

vdsm log:
==========
Thread-1265:INFO::2011-12-23 17:47:54,285::storage_connection::128::Storage.ServerConnection:(validae(Request to
validate NFS storage server)
Thread-1265:ERROR:2011-12-23 18:47:54,285::storage_connection::291::StoragerServerConnection::(__validadeFileServer)
Error during storage connection validation: __init__() got an unexpected keyword argument 'timeout'
Traceback (most recent call last):
File "/usr/share/vdsm/storage/storage_connection.py", line 264, in __validateFileServer
TypeError: __init()__ got an unexpected keyword argument 'timeout'

Change-Id: Ic64bf1bd366d1e9cb4c80c50b85a57ae022374cd
Reviewed-on: http://gerrit.ovirt.org/734
Reviewed-by: Dan Kenigsberg <danken@redhat.com>
Reviewed-by: Igor Lvovsky <ilvovsky@redhat.com>
Tested-by: Igor Lvovsky <ilvovsky@redhat.com>