Revert "net: unmanage bonds used for options gathering"
This reverts commit 1566036c547cf6d25894e51ae7e0f69d68ae5057.
OST upgrade from 4.1 to 4.2 is failing with:
DBusException: org.freedesktop.DBus.Error.AccessDenied: Property
"Managed" of interface "org.freedesktop.NetworkManager.Device" is not
settable

Change-Id: Icedcddd8d68fa4905e2ec48cd31109f204dd8ebb
Signed-off-by: Edward Haas <edwardh@redhat.com>