py3, storage: Iterate static list of tasks dictionary while clearing it
Fix exception met for calling TaskManager.unloadTasks() on python 3:

 File "vdsm/lib/vdsm/storage/taskManager.py", line 147, in unloadTasks
     for taskID, task in self._tasks.items():
 RuntimeError: dictionary changed size during iteration

At this point xfailing tests for python 3 now turn as XPASS,
so the marker is removed.

Change-Id: Ie31b3b4bad83d52331ffddd742fc8b6f9347af20
Signed-off-by: Amit Bawer <abawer@redhat.com>