tests: Fix child process leak in taskset tests
Almost all taskset tests leaked a child process, causing random failures
in the CI like this:

======================================================================
ERROR: test_set_from_parent(frozenset((1, 2))) (taskset_test.AffinityTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 133, in run
    self.runTest(result)
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 151, in runTest
    test(result)
  File "/usr/lib64/python2.7/unittest/case.py", line 431, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib64/python2.7/unittest/case.py", line 342, in run
    result.startTest(self)
  File "/usr/lib/python2.7/site-packages/nose/proxy.py", line 170, in startTest
    self.result.startTest(self.test)
  File "/vdsm/tests/testlib.py", line 404, in startTest
    self.stream.flush()
IOError: [Errno 4] Interrupted system call

Confirmed by our process leak check:

$ ./run_tests_local.sh --with-process-leak-check taskset_test.py
...
======================================================================
ERROR: test_get (taskset_test.AffinityTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 133, in run
    self.runTest(result)
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 151, in runTest
    test(result)
AssertionError: Test leaked child processes:
[
    {
        "cmdline": [],
        "pid": 26456
    }
]

Fixed by waiting for the process, see:
https://docs.python.org/2/library/multiprocessing.html#multiprocessing.Process.join

Change-Id: Ia1863b669a143b54697cf14209a44f8bdbd1411e
Signed-off-by: Nir Soffer <nsoffer@redhat.com>