tests: temporarily exclude few tests to restore CI
A few network tests require the TUN device, which is not available
under mock environments.

Furthermore, when run under the new CI infrastructure which leverages mock,
we can see this error:

======================================================================
ERROR: testGetBondingOptions (netinfoTests.TestNetinfo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/run/tests/monkeypatch.py", line 133, in wrapper
    return f(*args, **kw)
  File "/tmp/run/tests/testValidation.py", line 105, in wrapper
    return f(*args, **kwargs)
  File "/tmp/run/tests/testValidation.py", line 145, in wrapper
    return f(*args, **kwargs)
  File "/tmp/run/tests/netinfoTests.py", line 290, in
testGetBondingOptions
    with open(netinfo.BONDING_MASTERS, 'w') as bonds:
IOError: [Errno 13] Permission denied: '/sys/class/net/bonding_masters'
-------------------- >> begin captured logging << --------------------
root: DEBUG: /sbin/modprobe bonding (cwd None)
root: DEBUG: FAILED: <err> = ''; <rc> = 1
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------

This happens if the system cannot load modules inside the chrooted
mock environments.

We temporarily NOSE_EXCLUDE away the problematic jobs in order to
restore CI automated tests. We will restore those tests ASAP once
fixed to run properly in mocked environments.

Change-Id: I1721a0e2fccb9f8fff216f866843fa1daf192185
Signed-off-by: Francesco Romani <fromani@redhat.com>
Reviewed-on: https://gerrit.ovirt.org/45134
Reviewed-by: Ondřej Svoboda <osvoboda@redhat.com>
Reviewed-by: Dan Kenigsberg <danken@redhat.com>
Continuous-Integration: Dan Kenigsberg <danken@redhat.com>
Reviewed-on: https://gerrit.ovirt.org/45264
Reviewed-by: Adam Litke <alitke@redhat.com>