tests: Mark test as broken on oVirt CI.
Recently my builds fail randomly because of this test:

======================================================================
FAIL: test_detect_slow_client_concurrency(True) (protocoldetector_test.AcceptorTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/workspace/vdsm_standard-check-patch/vdsm/tests/testlib.py", line 142, in wrapper
    return f(self, *args)
  File "/home/jenkins/workspace/vdsm_standard-check-patch/vdsm/tests/protocoldetector_test.py", line 167, in test_detect_slow_client_concurrency
    self.check_concurrently(self.check_slow_client, use_ssl)
  File "/home/jenkins/workspace/vdsm_standard-check-patch/vdsm/tests/protocoldetector_test.py", line 266, in check_concurrently
    self.assertTrue(all(done))
AssertionError: False is not true

Mark it as broken on oVirt CI until we have time to dig deeper.

Change-Id: Ibed170270234a22896949dc5fadb81659c186ad3
Signed-off-by: Nir Soffer <nsoffer@redhat.com>