sslutils: Fix "SSLSocket.makefile" for py2
When working on [1] a regression has been introduced - py2 won't accept
calling the "socket.socket.makefile" method with "self" bound to
"sslutils.SSLSocket" instance:

 TypeError: unbound method makefile() must be called with _socketobject instance as first argument (got SSLSocket instance instead)

Python 3 handles it well. This patch restores the previous code version
for py2.

[1] https://gerrit.ovirt.org/#/c/102950/

Change-Id: Ie7a7b37e748321f8214987b8b6fddb44bacff6f9
Signed-off-by: Marcin Sobczyk <msobczyk@redhat.com>