supervdsm_api: Unbreak vdsm startup
Commit afc30514c47b (storage: use modern way how to call supervdsm in
devicemapper) added a file in supervdsm_api/ but did not added it to
Makefile.am. The surprising result is that building rpms and installing
vdsm succeed, but the calling the new supervdsm API during
HSM.__init__() cause vdsm to panic.

In vdsm log we see that vdsm was terminated without any error message:

2019-09-19 16:25:07,732-0400 INFO  (MainThread) [vds] (PID: 9202) I am
the actual vdsm 4.40.0.905.git756ee1f lago-basic-suite-master-host-0
(3.10.0-957.21.3.el7.x86_64) (vdsmd:150)

2019-09-19 16:25:07,733-0400 INFO  (MainThread) [vds] VDSM will run with
cpu affinity: frozenset([1]) (vdsmd:262)

2019-09-19 16:25:07,742-0400 INFO  (MainThread) [storage.HSM] START HSM
init (hsm:373)

2019-09-19 16:25:07,748-0400 INFO  (MainThread) [storage.HSM] Creating
data-center mount directory '/rhev/data-center/mnt' (hsm:378)

2019-09-19 16:25:07,748-0400 INFO  (MainThread) [storage.fileUtils]
Creating directory: /rhev/data-center/mnt mode: None (fileUtils:197)

2019-09-19 16:25:07,941-0400 INFO  (MainThread) [storage.udev]
Registering multipath event monitor <vdsm.storage.mpathhealth.Monitor
object at 0x7f32b8672450> (udev:182)

2019-09-19 16:25:07,941-0400 INFO  (MainThread) [storage.udev] Starting
multipath event listener (udev:116)

Then vdsm starts again:

2019-09-19 16:25:13,505-0400 INFO  (MainThread) [vds] (PID: 9900) I am
the actual vdsm 4.40.0.905.git756ee1f lago-basic-suite-master-host-0
(3.10.0-957.21.3.el7.x86_64) (vdsmd:150)

This continues forever.

In /var/log/message we find the exception:

Sep 19 16:45:44 lago-basic-suite-master-host-0 vdsm[3151]: ERROR Panic: Error initializing IRS
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/vdsm/vdsmd.py", line 95, in serve_clients
    irs = Dispatcher(HSM())
  File "/usr/lib/python2.7/site-packages/vdsm/storage/hsm.py", line 409, in __init__
    self.multipathListener.start()
  File "/usr/lib/python2.7/site-packages/vdsm/storage/udev.py", line 139, in start
    self._start_monitors(self._monitors)
  File "/usr/lib/python2.7/site-packages/vdsm/storage/udev.py", line 273, in _start_monitors
    m.start()
  File "/usr/lib/python2.7/site-packages/vdsm/storage/mpathhealth.py", line 85, in start
    for guid, paths in devicemapper.multipath_status().items():
  File "/usr/lib/python2.7/site-packages/vdsm/storage/devicemapper.py", line 201, in multipath_status
    return supervdsm.getProxy().devicemapper_multipath_status()
  File "/usr/lib/python2.7/site-packages/vdsm/common/supervdsm.py", line 56, in __call__
    return callMethod()
  File "/usr/lib/python2.7/site-packages/vdsm/common/supervdsm.py", line 53, in <lambda>
    getattr(self._supervdsmProxy._svdsm, self._funcName)(*args,
AttributeError: 'AutoProxy[instance]' object has no attribute 'devicemapper_multipath_status'

And the panic message:

Sep 19 16:45:44 lago-basic-suite-master-host-0 systemd: vdsmd.service:
main process exited, code=killed, status=9/KILL

So we have a logging issue for errors during HSM.__init__(). I only
added the missing file to Makefile.am. We will have to improve logging
later to make it easier to debug such issues.

Change-Id: I4439c183a153d3fef53ba7573ceb273da4257e01
Signed-off-by: Nir Soffer <nsoffer@redhat.com>