automation: Unspecify version for ovirt-imageio-common
This was required during transition from version 2.0.5 to 2.0.6
but now results in an outdated lookup for CI dependency:

 Error: Unable to find a match: ovirt-imageio-common-2.0.6

Change-Id: I6155489e595521ed260a454d27121581ab26839b
Signed-off-by: Amit Bawer <abawer@redhat.com>