tool: Fix TypeError when configuration check fails
When is-configured and validate-config failed for some modules, we got a
TypeError trying to join a list of configurator objects, instead of list
of strings.

    TypeError: sequence item 0: expected string, Sanlock found

Change-Id: Ic2fde1ddbbb9584429a4c190d38a2817e5a6dfb1
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1127877
Signed-off-by: Nir Soffer <nsoffer@redhat.com>
Reviewed-on: http://gerrit.ovirt.org/31782
Reviewed-by: Yaniv Bronhaim <ybronhei@redhat.com>
Reviewed-by: mooli tayer <mtayer@redhat.com>
Reviewed-by: Dan Kenigsberg <danken@redhat.com>
Reviewed-on: http://gerrit.ovirt.org/32061
Tested-by: mooli tayer <mtayer@redhat.com>