spbackends: fix setSpmStatus signature
Now that we log exceptions in stopSpm, we can see that the call always
fails when using the memory backend:

2021-05-20 17:10:24,173+0300 ERROR (jsonrpc/7) [storage.StoragePool] Error updating SPM status (sp:468)
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/vdsm/storage/sp.py", line 465, in stopSpm
    __securityOverride=True)
  File "/usr/lib/python3.6/site-packages/vdsm/storage/securable.py", line 79, in wrapper
    return method(self, *args, **kwargs)
TypeError: setSpmStatus() missing 1 required positional argument: 'lVer'

This failure is fine since the memory backend drop the provided values.
Fix the method signature to avoid this failure.

Change-Id: I95d2d592deed557a4365a1c3d0d5e550fbc5d5fd
Signed-off-by: Nir Soffer <nsoffer@redhat.com>