tests: Fix non-daemon thread leak in pthread_test
When testing the pthread module, we cannot use our concurrent.thread()
helper to start threds, since it is using the pthread module. The test
was using raw threaing.Thread, and failed to use it correctly, leaking
non-daemon thread after the test. This can cause the testrunner process
to never terminate, waiting until the non-daemon thread exits.

The leak can be detected by running --with-thread-leak-check several
times:

$ ./run_tests_local.sh --with-thread-leak-check common/pthread_test.py
nose.config: INFO: Ignoring files matching ['^\\.', '^_', '^setup\\.py$']
common.pthread_test.PthreadNameTests
    test_name_is_set                                            OK
ERROR
    test_name_set_doesnt_change_parent                          OK
    test_name_too_long                                          OK

======================================================================
ERROR: test_name_is_set (common.pthread_test.PthreadNameTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 133, in run
    self.runTest(result)
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 151, in runTest
    test(result)
  File "/usr/lib64/python2.7/unittest/case.py", line 431, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib64/python2.7/unittest/case.py", line 408, in run
    result.stopTest(self)
  File "/usr/lib/python2.7/site-packages/nose/proxy.py", line 177, in stopTest
    self.plugins.stopTest(self.test)
  File "/usr/lib/python2.7/site-packages/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/usr/lib/python2.7/site-packages/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "/home/nsoffer/src/vdsm/tests/testValidation.py", line 114, in stopTest
    raise Exception('This test leaked threads: %s ' % leaked_threads)
Exception: This test leaked threads: frozenset([<Thread(Thread-1, started 140206643451648)>])

The code had several common errors:

1. Creating a non-daemon thread
2. Not joining the thread
3. Not signaling the thread if the test assertion failed, leaving a
   running non-daemon thread that will never exit.

This change fixes the stuck build issue after the test runner process
timed out.

Change-Id: If08c8cbb8020dc58427a4aa848b6cb45e4fbfe0a
Signed-off-by: Nir Soffer <nsoffer@redhat.com>