storage.exception: Fix cleared metadata regressions
In commit 5ec4428c4d2e (upgrade: Skip volumes with cleared metadata) we
added a new specific exception for the special case of cleared metadata.
This broke error handlers expecting MetaDataKeyNotFoundError:

- volume.Volume.getLeagality(), volume.Volume.isLeagal(), and
  volume.Volume.isFake() pretend that volume with invalid metadata is
  legal. This looks very wrong but we don't know if the new behaviour is
  safe.

- volume.Volume.validateDelate() allows deleting of a volume with
  missing key, assuming that the reason for the missing key is
  partly-deleted volume. Now it disallow deleting partly deleted volume.

- formatconveter.v3DomainConverter() was skipping volume size fix if
  metadata key is missing. Now it will abort conversion if a volume with
  cleared metadata is found.

This change restores the original behaviour, handling both missing key
and cleared metadata in these cases.

Change-Id: I8a79475b5f975ac7bcad08236420a09f2a59496a
Bug-Url: https://bugzilla.redhat.com/1713724
Signed-off-by: Nir Soffer <nsoffer@redhat.com>