storage.exception: LVMError in LVDoesNotExistError
Make LogicalVolumeDoesNotExistsError exception to inherit from
_HoldingLVMCommandError exception, so that we allow logging the
error and make the exception more informative.

Signed-off-by: Albert Esteve <aesteve@redhat.com>