spec: Require sanlock version handling EINTR
libsanlock was not handling EINTR, causing failures in sanlock calls
if vdsm received a signal while libsnalock was blocked in a syscall.
A typical case is when a child process terminates and vdsm receives a
SIGCHLD signal.

When this happens, the vdsm operation fails with this error:

    SanlockException: (4, 'Sanlock ...', 'Interrupted system call')

Change-Id: Ied259bcf6a2200d649268e6e16ea9e80ed10250c
Bug-Url: https://bugzilla.redhat.com/1356676
Signed-off-by: Allon Mureinik <amureini@redhat.com>