travis: Upgrade distribution to bionic
Upgrading to bionic fixes random failure with creating loop device with
sector size of 4k.

With this patch, all loop devices are created successfully[1]:

python3 tests/storage/userstorage.py setup
[userstorage] INFO    Creating backing file /var/tmp/vdsm-storage/backing.file-512
[userstorage] INFO    Creating loop device /var/tmp/vdsm-storage/loop.file-512
[userstorage] INFO    Creating filesystem /var/tmp/vdsm-storage/mount.file-512
[userstorage] INFO    Creating file /var/tmp/vdsm-storage/mount.file-512/file
[userstorage] INFO    Creating backing file /var/tmp/vdsm-storage/backing.file-4k
[userstorage] INFO    Creating loop device /var/tmp/vdsm-storage/loop.file-4k
[userstorage] INFO    Creating filesystem /var/tmp/vdsm-storage/mount.file-4k
[userstorage] INFO    Creating file /var/tmp/vdsm-storage/mount.file-4k/file
[userstorage] INFO    Creating backing file /var/tmp/vdsm-storage/backing.mount-512
[userstorage] INFO    Creating loop device /var/tmp/vdsm-storage/loop.mount-512
[userstorage] INFO    Creating filesystem /var/tmp/vdsm-storage/mount.mount-512
[userstorage] INFO    Creating backing file /var/tmp/vdsm-storage/backing.mount-4k
[userstorage] INFO    Creating loop device /var/tmp/vdsm-storage/loop.mount-4k
[userstorage] INFO    Creating filesystem /var/tmp/vdsm-storage/mount.mount-4k

Without this patch, system fail to create loop device with 4k sector
sizei[2]:

python3 tests/storage/userstorage.py setup
[userstorage] INFO    Creating backing file /var/tmp/vdsm-storage/backing.file-512
[userstorage] INFO    Creating loop device /var/tmp/vdsm-storage/loop.file-512
[userstorage] INFO    Creating filesystem /var/tmp/vdsm-storage/mount.file-512
[userstorage] INFO    Creating file /var/tmp/vdsm-storage/mount.file-512/file
[userstorage] INFO    Creating backing file /var/tmp/vdsm-storage/backing.file-4k
[userstorage] INFO    Creating loop device /var/tmp/vdsm-storage/loop.file-4k
losetup: /dev/loop1: set logical block size failed: Resource temporarily unavailable
Traceback (most recent call last):
  File "tests/storage/userstorage.py", line 296, in <module>
    main()
  File "tests/storage/userstorage.py", line 275, in main
    setup(args)
  File "tests/storage/userstorage.py", line 284, in setup
    p.setup()
  File "tests/storage/userstorage.py", line 202, in setup
    self._mount.setup()
  File "tests/storage/userstorage.py", line 142, in setup
    self._loop.setup()
  File "tests/storage/userstorage.py", line 81, in setup
    device = self._create_loop_device()
  File "tests/storage/userstorage.py", line 116, in _create_loop_device
    out = subprocess.check_output(cmd)
  File "/usr/lib64/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['sudo', 'losetup', '-f',
'/var/tmp/vdsm-storage/backing.file-4k', '--show', '--sector-size',
'4096']' returned non-zero exit status 1.

Looks like the newer kernel in bionic (5.3.0) works better for us.

[1] https://travis-ci.org/github/nirs/vdsm/jobs/707361262
[2] https://travis-ci.org/github/nirs/vdsm/jobs/707420014

Change-Id: Ie869f302293b1119fd21ba366f1900ab3a97c0a6
Signed-off-by: Nir Soffer <nsoffer@redhat.com>