libvirtvm: Avoiding snapshot metadata creation
After creating a new snapshot, it is not possible to live-migrate:

  libvirtError: Requested operation is not valid: cannot migrate domain
with 1 snapshots

Issue is also affecting storage live migration due to use of the same vm
snapshot function during the live storage migration process.

This patch introduces the libvirt flag needed to avoid snapshot metadata
creation.

Bug-Url: http://bugzilla.redhat.com/872277
Change-Id: I928983a404f822522a0a48218f9c58fa8d6296b1
Signed-off-by: Amador Pahim <apahim@redhat.com>
Reviewed-on: http://gerrit.ovirt.org/9139
Reviewed-by: Federico Simoncelli <fsimonce@redhat.com>