tests: use also image ID for storing prepared volumes
Current implementation of fake prepared volumes would
fail for teardownImage() as it doesn't pass vol_id into the call,
resulting into calling fake teardownImage() with vold_id=None:

    File "/home/vjuranek/ovirt/vdsm/tests/virt/vmfakelib.py", line 99, in teardownImage
        del self.prepared_volumes[(sdUUID, volUUID)]
    KeyError: ('d3adaee4-34d6-4691-a51d-48dd9096091f', None)

Add image ID into the prepared volumes key, so that the key is now
(sd_id, img_id, vol_id).

In rela code volume ID is never used and all volumes belonging to the
image are deactiveted, there also in the fake implementation all the
volumes for specified image are removed.

Change-Id: I10be0c197d610773e48896671123f69950338ee9
Signed-off-by: Vojtech Juranek <vjuranek@redhat.com>