py3-gluster: Fixed other verbs using py3 updated _execGluster function
With the removal of a deprecated execcmd function in gluster/cli.py
https://gerrit.ovirt.org/#/c/104723/
some verbs were still using old (rc,out,err) format, hence encountering
errors.

example error:
File "<string>", line 2, in glusterVolumeSetHelpXml
  File "/usr/lib64/python3.6/multiprocessing/managers.py", line 772, in _callmethod
    raise convert_to_error(kind, result)
ValueError: too many values to unpack (expected 3)

This patch fixes the above.

Change-Id: I0295bb5dd4990de38b3dca88a691203a4de6da3a
Signed-off-by: Kaustav Majumder <kmajumde@redhat.com>