virt: Fix circular imports in livemerge, snapshot
When snapshot and livemerge modules were created, the code was moved
from vm module, creating circular dependencies. Because the vm module is
imported early during runtime, the dependency was hidden. But when
trying to run the new merge_test.py manually, collecting the tests fail
with:

______________ ERROR collecting tests/virt/merge_test.py _______________
ImportError while importing test module 'tests/virt/merge_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
virt/merge_test.py:31: in <module>
    from vdsm.virt.livemerge import (
../lib/vdsm/virt/livemerge.py:33: in <module>
    from vdsm.virt import vm
../lib/vdsm/virt/vm.py:66: in <module>
    from vdsm.virt.livemerge import DriveMerger
E   ImportError: cannot import name 'DriveMerger' from partially initialized module
'vdsm.virt.livemerge' (most likely due to a circular import) (lib/vdsm/virt/livemerge.py)

The issue in was StorageUnavailableError, defined in the vm module. Fix
by introducing vdsm.virt.errors modules, a place for internal errors
shared by the virt package.

The new module contains now only the StorageUnavailableError, to solve
the circular dependency. We can move all other internal errors there to
clean up the mess.

Change-Id: I3d923b986933c62414e7737431ca9f0fc762a0bb
Signed-off-by: Nir Soffer <nsoffer@redhat.com>