sp: Simplify stopSpm and improve panic log
We tried to perform all operations during stopSpm, and panic at the end
if any of the operation failed:

1. Unmount master mount
2. Stopping SPM mail monitor
3. Releasing the SPM lease

This can be simplified by calling panic() on the first failure.  When we
panic, the process terminates, so all mailbox threads will be stooped.
Sanlock will detect vdsm termination and release the SPM lease.

A nice side effect is that panic() is called in an exception handler in
stopSpm, so it logs a proper traceback:

    2021-05-22 01:15:07,314+0300 ERROR (jsonrpc/2) [root] Panic: Error releasing cluster lock (panic:31)
    Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/vdsm/storage/clusterlock.py", line 610, in release
        slkfd=SANLock._process_fd)
    sanlock.SanlockException: (1, 'Sanlock resource not released', 'Operation not permitted')

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/vdsm/storage/sp.py", line 465, in stopSpm
        self.masterDomain.releaseClusterLock()
      File "/usr/lib/python3.6/site-packages/vdsm/storage/sd.py", line 1252, in releaseClusterLock
        self._manifest.releaseDomainLock()
      File "/usr/lib/python3.6/site-packages/vdsm/storage/sd.py", line 580, in releaseDomainLock
        self._domainLock.release(self.getDomainLease())
      File "/usr/lib/python3.6/site-packages/vdsm/storage/clusterlock.py", line 618, in release
        raise se.ReleaseLockFailure(self._sdUUID, e)
    vdsm.storage.exception.ReleaseLockFailure: Cannot release lock: ('8ef0cc64-77c5-49e0-a0f5-03cee9bbee20',
    SanlockException(1, 'Sanlock resource not released', 'Operation not permitted'))

Before this patch, the panic message was:

    2021-05-22 00:18:04,569+0300 ERROR (jsonrpc/7) [root] Panic:
    Unrecoverable errors during SPM stop process. (panic:31)
    NoneType: None

"NoneType: None" is the result of logging an error with exc_info=True
when we are not in an exception handler.

Change-Id: Ib397bae38edd9aa3a81d842f05531b6f8c5916c9
Signed-off-by: Nir Soffer <nsoffer@redhat.com>