exception: Inherit from VdsmException
All exceptions used by vdsm API inherit now from VdsmException, removing
duplicate code for generating response.

The info() method added recently to GeneralException was moved up to
VdsmException. Use new info to simplify GlusterException base class.

Change-Id: I25ffdd531fc9878a6762e2c0f670134b3aedf9a0
Signed-off-by: Nir Soffer <nsoffer@redhat.com>
Reviewed-on: https://gerrit.ovirt.org/48869
Reviewed-by: Francesco Romani <fromani@redhat.com>
Reviewed-by: Piotr Kliczewski <piotr.kliczewski@gmail.com>
Continuous-Integration: Jenkins CI