virt net: Interface default driver name set to 'vhost'
When following these steps:
- Create a VM with vnic_profile that has queues custom properties.
- Start the VM.
- Hot-unplug the vNIC from the VM.

An exception occurs:
libvirtError: unsupported configuration:
    Unknown interface <driver name=''> has been specified

Due to a missing default driver name.

Change-Id: I508675f9dd40ba70803938902a1c2f8fced00504
Bug-Url: https://bugzilla.redhat.com/1470550
Signed-off-by: Edward Haas <edwardh@redhat.com>
Continuous-Integration: Jenkins CI
Tested-by: Meni Yakove <myakove@redhat.com>
Reviewed-by: Dan Kenigsberg <danken@redhat.com>
Reviewed-by: Petr Horáček <phoracek@redhat.com>
(cherry picked from commit 00308a4a9a4c666397655cc749e93a019b87e4dd)
Reviewed-by: Francesco Romani <fromani@redhat.com>