py3: vm: use appendChild(element) instead of etree_element
The minor modifications to vm.py are analogous to I60003e69702, needed
to avoid failures such as the following ones:

ERROR: test_onDeviceRemoved('dimm0', {'balloon'}) (virttests.vm_test.TestLibVirtCallbacks)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vdsm.git/tests/testlib.py", line 143, in wrapper
    return f(self, *args)
  File "/vdsm.git/tests/virttests/vm_test.py", line 1649, in test_onDeviceRemoved
    testvm.onDeviceRemoved(alias)
  File "/vdsm.git/lib/vdsm/virt/vm.py", line 5777, in onDeviceRemoved
    self._updateDomainDescriptor()
  File "/vdsm.git/tests/vmfakelib.py", line 288, in _updateDomainDescriptor
    fake._domain = DomainDescriptor(fake._buildDomainXML())
  File "/vdsm.git/lib/vdsm/virt/vm.py", line 2185, in _buildDomainXML
    return self._make_domain_xml()
  File "/vdsm.git/lib/vdsm/virt/vm.py", line 2233, in _make_domain_xml
    domxml._devices.appendChild(etree_element=dev)
  File "/vdsm.git/lib/vdsm/virt/vmxml.py", line 367, in appendChild
    append_child(self._elem, element, etree_element)
  File "/vdsm.git/lib/vdsm/virt/vmxml.py", line 232, in append_child
    element.append(etree_child)
TypeError: append() argument must be xml.etree.ElementTree.Element, not Element

ERROR: testSerialBios('serial', 'x86_64', True, True) (virttests.vm_test.TestVm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vdsm.git/tests/testlib.py", line 143, in wrapper
    return f(self, *args)
  File "/vdsm.git/tests/virttests/vm_test.py", line 343, in testSerialBios
    dom_xml = fakevm._buildDomainXML()
  File "/vdsm.git/lib/vdsm/virt/vm.py", line 2185, in _buildDomainXML
    return self._make_domain_xml()
  File "/vdsm.git/lib/vdsm/virt/vm.py", line 2238, in _make_domain_xml
    domxml._devices.appendChild(etree_element=elem)
  File "/vdsm.git/lib/vdsm/virt/vmxml.py", line 367, in appendChild
    append_child(self._elem, element, etree_element)
  File "/vdsm.git/lib/vdsm/virt/vmxml.py", line 232, in append_child
    element.append(etree_child)
TypeError: append() argument must be xml.etree.ElementTree.Element, not Element

Change-Id: Ibd685b99982084df2d843f903d4b46144d4eccd2
Signed-off-by: Dan Kenigsberg <danken@redhat.com>