exception: add a helper for re-rasing with traceback
Current exceptions in lvm module do not show full traceback as
"raise ... from None" is used to prevent repeating errors.

Adding a helper to VdsmException that clears __cause__ and uses current
traceback in with_traceback() to provide a meaningful traceback.

This is not specific to lvm.py module and can be used anywhere.

OLD:
Traceback (most recent call last):
  File "/vdsm/tests/storage/lvm_test.py", line 277, in test_failed_removevg_cache
    lvm.removeVG("vg")
  File "/vdsm/lib/vdsm/storage/lvm.py", line 1462, in removeVG
    raise se.VolumeGroupRemoveError(e.cmd, e.rc, e.out, e.err) from None
vdsm.storage.exception.VolumeGroupRemoveError: Volume Group remove error: "cmd=fakecmd rc=5 out=['out'] err=['err']"

NEW:
Traceback (most recent call last):
  File "/vdsm/tests/storage/lvm_test.py", line 277, in test_failed_removevg_cache
    lvm.removeVG("vg")
  File "/vdsm/lib/vdsm/storage/lvm.py", line 1462, in removeVG
    raise se.VolumeGroupRemoveError(e.cmd, e.rc, e.out, e.err).with_exception(e)
  File "/vdsm/lib/vdsm/common/exception.py", line 47, in with_exception
    raise self.with_traceback(exc.__traceback__)
  File "/vdsm/lib/vdsm/storage/lvm.py", line 1457, in removeVG
    _lvminfo.run_command(cmd, devices=_lvminfo._getVGDevs((vgName, )))
  File "/vdsm/lib/vdsm/storage/lvm.py", line 564, in run_command
    raise error
  File "/vdsm/lib/vdsm/storage/lvm.py", line 539, in run_command
    return self._runner.run(full_cmd)
  File "/vdsm/lib/vdsm/storage/lvm.py", line 348, in run
    rc, out, err = self._run_command(cmd)
  File "/vdsm/tests/storage/lvm_test.py", line 199, in _run_command
    raise se.LVMCommandError("fakecmd", 5, ["out"], ["err"])
vdsm.storage.exception.VolumeGroupRemoveError: Volume Group remove error: "cmd=fakecmd rc=5 out=['out'] err=['err']"

Signed-off-by: Roman Bednar <rbednar@redhat.com>
Bug-Url: https://bugzilla.redhat.com/1536880
Change-Id: I984d6c761fc1fa206d2d8b75b4578db0a6dca13a