py-watch: Terminate watched process if terminated
Since we started to use py-watch, interrupting the tests terminates
py-watch but leaves stale detached python test process spamming your
terminal.

Change py-watch to terminate the watched process if py-watch was
terminated or interrupted.

Here is an example interrupted test run:

$ tox -e storage-py27
...
storage/asyncevent_test.py ..................................
storage/asyncutils_test.py .....
storage/blkdiscard_test.py ..
storage/blockdev_test.py ssss....s
storage/blocksd_test.py ........x.................sssssss
storage/blockvolume_test.py ...........^Cpy-watch: Terminated by signal 2
ERROR: KEYBOARDINTERRUPT
profile: Interrupted
ERROR: keyboardinterrupt

Change-Id: Ic1b05f616225f2db23c6beb3fb50867b3264e6ef
Signed-off-by: Nir Soffer <nsoffer@redhat.com>