py3: decode headers retuned by curl
Decode output from curl before parsing headers. This is needed to be
compatible with python3 (see bellow example of error in python3).

Headers are expected to be strings, therefore we decode byte output from
curl command. As we use it for interaction with other external service
(like OpenStack Glance), we assume that headers contain only ASCII
charactes as specified by RFC 2822.

Decoding and parsing curl output is done in dedicated function to make
testing more easy. The patch also contains test for this function which
tests parsing headers from Glance server when oVirt downloads image from
Glance.

Example of error in python3:

    File "/usr/lib/python3.6/site-packages/vdsm/storage/curlImgWrap.py", line 65, in <listcomp>
	return dict([x.split(": ", 1) for x in out[1:-1]])
    TypeError: a bytes-like object is required, not 'str'

Change-Id: Id48cf27df88c6da141e61972c5b985ab789e2779
Signed-off-by: Vojtech Juranek <vjuranek@redhat.com>