python3: Explicitly convert to int
Python 3 does not convert float to int when performing bitwise
operations, failing with:

    TypeError: unsupported operand type(s) for &: 'float' and 'int'

Fix by converting the argument to int in the caller.

Change-Id: Id068d11395e938bc70f15356bcbcea192c0d4a8c
Signed-off-by: Nir Soffer <nsoffer@redhat.com>