virt: Improve thread safety of QemuGuestAgentPoller
We should protect looping over QemuGuestAgentPoller._capabilities and
QemuGuestAgentPoller._last_failure_lock with locks, in order to prevent
failures on changed dictionary contents.  Here is an example of such a failure
spotted in logs:

  ERROR (qgapoller/0) [virt.periodic.Operation] <bound method QemuGuestAgentPoller._cleanup of <vdsm.virt.qemuguestagent.QemuGuestAgentPoller object at 0x3c47810>> operation failed (periodic:215)
  Traceback (most recent call last):
    File "/usr/lib/python2.7/site-packages/vdsm/virt/periodic.py", line 213, in __call__
      self._func()
    File "/usr/lib/python2.7/site-packages/vdsm/virt/qemuguestagent.py", line 201, in _cleanup
      for vm_id in self._capabilities:
  RuntimeError: dictionary changed size during iteration

When capabilities update is under lock now, we perform it only if the
capabilities are changed.

Change-Id: I8da31d4efa95038451cb7938111d3074ebcac1b4
Signed-off-by: Milan Zamazal <mzamazal@redhat.com>