sampling: a quick fix to make vdsm run again
commit c506391442bc was merged too quickly, leaving a process that fails
to start due to
    AttributeError: 'HostStatsThread' object has no a ttribute 'nics'

Change-Id: Idc993a6b1284345805455a63e3926bc2893d5874
Signed-off-by: Dan Kenigsberg <danken@redhat.com>
Reviewed-on: http://gerrit.ovirt.org/13902
Reviewed-by: Mark Wu <wudxw@linux.vnet.ibm.com>
Tested-by: Daniel Erez <derez@redhat.com>
Reviewed-by: Daniel Erez <derez@redhat.com>